# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ramon/wkspace/xdma_1_ex/imports/xilinx_pcie_xdma_ref_board.xdc

# IP: ip/xdma_1/xdma_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_1 || ORIG_REF_NAME==xdma_1} -quiet] -quiet
