# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.cache/wt [current_project]
set_property parent.project_path /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.8 [current_project]
set_property ip_output_repo /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv /home/ramon/wkspace/xdma_1_ex/imports/xilinx_dma_pcie_ep.sv
read_verilog -library xil_defaultlib /home/ramon/wkspace/xdma_1_ex/imports/xdma_app.v
read_ip -quiet /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/xdma_1/xdma_1.xci
set_property used_in_implementation false [get_files -all /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/xdma_1/xdma_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/xdma_1/source/xdma_1_pcie3_7vx_ip.xdc]
set_property used_in_implementation false [get_files -all /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/xdma_1/synth/xdma_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/xdma_1/ip_0/source/xdma_1_pcie3_ip-PCIE_X0Y1.xdc]
set_property used_in_implementation false [get_files -all /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/xdma_1/ip_0/synth/xdma_1_pcie3_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/xdma_1/ip_1/xdma_v4_1_2_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/xdma_1/ip_2/xdma_v4_1_2_blk_mem_64_noreg_be_ooc.xdc]

read_ip -quiet /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/ramon/wkspace/xdma_1_ex/xdma_1_ex.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ramon/wkspace/xdma_1_ex/imports/xilinx_pcie_xdma_ref_board.xdc
set_property used_in_implementation false [get_files /home/ramon/wkspace/xdma_1_ex/imports/xilinx_pcie_xdma_ref_board.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top xilinx_dma_pcie_ep -part xc7vx690tffg1761-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xilinx_dma_pcie_ep.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xilinx_dma_pcie_ep_utilization_synth.rpt -pb xilinx_dma_pcie_ep_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
